<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu sebelum diisi
        DB::table('accounts')->truncate();

        $data = [
            ['id' => 594, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '1.1.01.01', 'nama_akun' => 'Kas Tunai', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 595, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '1.1.01.02', 'nama_akun' => 'Kas Kas Kecil', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 596, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '1.1.01.03', 'nama_akun' => 'Kas di Bank BRI', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 597, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 5, 'kode_akun' => '1.1.01.05', 'nama_akun' => 'Kas di Bank Mandiri', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 598, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 6, 'kode_akun' => '1.1.01.06', 'nama_akun' => 'Kas di Bank BNI', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 599, 'parent_id' => 111, 'lev1' => 1, 'lev2' => 1, 'lev3' => 1, 'lev4' => 7, 'kode_akun' => '1.1.01.07', 'nama_akun' => 'Kas di Bank BCA', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 600, 'parent_id' => 112, 'lev1' => 1, 'lev2' => 1, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '1.1.02.01', 'nama_akun' => 'Deposito', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 601, 'parent_id' => 112, 'lev1' => 1, 'lev2' => 1, 'lev3' => 2, 'lev4' => 2, 'kode_akun' => '1.1.02.02', 'nama_akun' => 'Obligasi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 602, 'parent_id' => 112, 'lev1' => 1, 'lev2' => 1, 'lev3' => 2, 'lev4' => 3, 'kode_akun' => '1.1.02.03', 'nama_akun' => 'Saham', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 603, 'parent_id' => 113, 'lev1' => 1, 'lev2' => 1, 'lev3' => 3, 'lev4' => 2, 'kode_akun' => '1.1.03.02', 'nama_akun' => 'Piutang Karyawan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 604, 'parent_id' => 113, 'lev1' => 1, 'lev2' => 1, 'lev3' => 3, 'lev4' => 3, 'kode_akun' => '1.1.03.03', 'nama_akun' => 'Piutang Lain', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 605, 'parent_id' => 114, 'lev1' => 1, 'lev2' => 1, 'lev3' => 4, 'lev4' => 1, 'kode_akun' => '1.1.04.01', 'nama_akun' => 'Cadangan Kerugian Piutang', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 606, 'parent_id' => 115, 'lev1' => 1, 'lev2' => 1, 'lev3' => 5, 'lev4' => 1, 'kode_akun' => '1.1.05.01', 'nama_akun' => 'Persediaan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 607, 'parent_id' => 115, 'lev1' => 1, 'lev2' => 1, 'lev3' => 5, 'lev4' => 2, 'kode_akun' => '1.1.05.02', 'nama_akun' => 'Persediaan Bengkel', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 608, 'parent_id' => 116, 'lev1' => 1, 'lev2' => 1, 'lev3' => 6, 'lev4' => 1, 'kode_akun' => '1.1.06.01', 'nama_akun' => 'Rekening Antar Kantor', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 609, 'parent_id' => 121, 'lev1' => 1, 'lev2' => 2, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '1.2.01.01', 'nama_akun' => 'Tanah', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 610, 'parent_id' => 121, 'lev1' => 1, 'lev2' => 2, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '1.2.01.02', 'nama_akun' => 'Gedung & Bangunan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 611, 'parent_id' => 121, 'lev1' => 1, 'lev2' => 2, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '1.2.01.03', 'nama_akun' => 'Kendaraan dan Mesin', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 612, 'parent_id' => 121, 'lev1' => 1, 'lev2' => 2, 'lev3' => 1, 'lev4' => 4, 'kode_akun' => '1.2.01.04', 'nama_akun' => 'Inventaris/Peralatan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 613, 'parent_id' => 122, 'lev1' => 1, 'lev2' => 2, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '1.2.02.01', 'nama_akun' => 'Akumulasi penyusutan Gedung dan Bangunan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 614, 'parent_id' => 122, 'lev1' => 1, 'lev2' => 2, 'lev3' => 2, 'lev4' => 2, 'kode_akun' => '1.2.02.02', 'nama_akun' => 'Akumulasi penyusutan Kendaraan dan Mesin', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 615, 'parent_id' => 122, 'lev1' => 1, 'lev2' => 2, 'lev3' => 2, 'lev4' => 3, 'kode_akun' => '1.2.02.03', 'nama_akun' => 'Akumulasi penyusutan Inventaris/Peralatan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 616, 'parent_id' => 123, 'lev1' => 1, 'lev2' => 2, 'lev3' => 3, 'lev4' => 1, 'kode_akun' => '1.2.03.01', 'nama_akun' => 'Biaya Pendirian Organisasi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 617, 'parent_id' => 123, 'lev1' => 1, 'lev2' => 2, 'lev3' => 3, 'lev4' => 2, 'kode_akun' => '1.2.03.02', 'nama_akun' => 'Lisensi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 618, 'parent_id' => 123, 'lev1' => 1, 'lev2' => 2, 'lev3' => 3, 'lev4' => 3, 'kode_akun' => '1.2.03.03', 'nama_akun' => 'Sewa dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 619, 'parent_id' => 123, 'lev1' => 1, 'lev2' => 2, 'lev3' => 3, 'lev4' => 4, 'kode_akun' => '1.2.03.04', 'nama_akun' => 'Asuransi dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 620, 'parent_id' => 124, 'lev1' => 1, 'lev2' => 2, 'lev3' => 4, 'lev4' => 1, 'kode_akun' => '1.2.04.01', 'nama_akun' => 'Akumulasi Amortisasi Biaya Pendirian Organisasi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 621, 'parent_id' => 124, 'lev1' => 1, 'lev2' => 2, 'lev3' => 4, 'lev4' => 2, 'kode_akun' => '1.2.04.02', 'nama_akun' => 'Akumulasi Amortisasi Lisensi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 622, 'parent_id' => 124, 'lev1' => 1, 'lev2' => 2, 'lev3' => 4, 'lev4' => 3, 'kode_akun' => '1.2.04.03', 'nama_akun' => 'Akumulasi Amortisasi Sewa dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 623, 'parent_id' => 124, 'lev1' => 1, 'lev2' => 2, 'lev3' => 4, 'lev4' => 4, 'kode_akun' => '1.2.04.04', 'nama_akun' => 'Akumulasi Amortisasi Asuransi dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 624, 'parent_id' => 125, 'lev1' => 1, 'lev2' => 2, 'lev3' => 5, 'lev4' => 1, 'kode_akun' => '1.2.05.01', 'nama_akun' => 'Konstruksi Dalam Pengerjaan dan Uang Muka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 625, 'parent_id' => 131, 'lev1' => 1, 'lev2' => 3, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '1.3.01.01', 'nama_akun' => 'Aset Lain-lain', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 626, 'parent_id' => 211, 'lev1' => 2, 'lev2' => 1, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '2.1.01.01', 'nama_akun' => 'Utang Dividen Pemdes', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 627, 'parent_id' => 211, 'lev1' => 2, 'lev2' => 1, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '2.1.01.02', 'nama_akun' => 'Utang Dividen Masy Penyerta Modal', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 628, 'parent_id' => 211, 'lev1' => 2, 'lev2' => 1, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '2.1.01.03', 'nama_akun' => 'Bantuan Sosial', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 629, 'parent_id' => 212, 'lev1' => 2, 'lev2' => 1, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '2.1.02.01', 'nama_akun' => 'Utang Operasional', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 630, 'parent_id' => 213, 'lev1' => 2, 'lev2' => 1, 'lev3' => 3, 'lev4' => 1, 'kode_akun' => '2.1.03.01', 'nama_akun' => 'Utang Pajak', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 631, 'parent_id' => 214, 'lev1' => 2, 'lev2' => 1, 'lev3' => 4, 'lev4' => 1, 'kode_akun' => '2.1.04.01', 'nama_akun' => 'Utang Pihak Ke-3', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 632, 'parent_id' => 214, 'lev1' => 2, 'lev2' => 1, 'lev3' => 4, 'lev4' => 2, 'kode_akun' => '2.1.04.02', 'nama_akun' => 'Utang lain-lain jangka pendek', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 633, 'parent_id' => 221, 'lev1' => 2, 'lev2' => 2, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '2.2.01.01', 'nama_akun' => 'Utang Bank 1', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 634, 'parent_id' => 221, 'lev1' => 2, 'lev2' => 2, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '2.2.01.02', 'nama_akun' => 'Utang Bank 2', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 635, 'parent_id' => 222, 'lev1' => 2, 'lev2' => 2, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '2.2.02.01', 'nama_akun' => 'Utang Jangka Panjang Lainnya', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 636, 'parent_id' => 311, 'lev1' => 3, 'lev2' => 1, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '3.1.01.01', 'nama_akun' => 'Modal Pemdes', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 637, 'parent_id' => 311, 'lev1' => 3, 'lev2' => 1, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '3.1.01.02', 'nama_akun' => 'Modal Penyertaan', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 638, 'parent_id' => 312, 'lev1' => 3, 'lev2' => 1, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '3.1.02.01', 'nama_akun' => 'Modal Lain-lain', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 639, 'parent_id' => 321, 'lev1' => 3, 'lev2' => 2, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '3.2.01.01', 'nama_akun' => 'Laba Ditahan s/d Tahun lalu', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 640, 'parent_id' => 322, 'lev1' => 3, 'lev2' => 2, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '3.2.02.01', 'nama_akun' => 'Laba/Rugi Tahun Berjalan', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 641, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '4.1.01.01', 'nama_akun' => 'Pasang Baru', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 642, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '4.1.01.02', 'nama_akun' => 'Pendapatan Abodemen', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 643, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '4.1.01.03', 'nama_akun' => 'Tagihan Pemakaian', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 644, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 4, 'kode_akun' => '4.1.01.04', 'nama_akun' => 'Denda', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 645, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 5, 'kode_akun' => '4.1.01.05', 'nama_akun' => 'Aktivasi Ulang', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 646, 'parent_id' => 411, 'lev1' => 4, 'lev2' => 1, 'lev3' => 1, 'lev4' => 6, 'kode_akun' => '4.1.01.06', 'nama_akun' => 'Pendapatan Lain-lain', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 647, 'parent_id' => 413, 'lev1' => 4, 'lev2' => 1, 'lev3' => 3, 'lev4' => 99, 'kode_akun' => '4.1.03.99', 'nama_akun' => 'Pendapatan Usaha Lainnya', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 648, 'parent_id' => 421, 'lev1' => 4, 'lev2' => 2, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '4.2.01.01', 'nama_akun' => 'Pendapatan Bunga Bank', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 649, 'parent_id' => 421, 'lev1' => 4, 'lev2' => 2, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '4.2.01.02', 'nama_akun' => 'Pendapatan Hadiah', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 650, 'parent_id' => 421, 'lev1' => 4, 'lev2' => 2, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '4.2.01.03', 'nama_akun' => 'Pendapatan Hibah', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 651, 'parent_id' => 421, 'lev1' => 4, 'lev2' => 2, 'lev3' => 1, 'lev4' => 4, 'kode_akun' => '4.2.01.04', 'nama_akun' => 'Pertambahan Nilai Penjualan Aset', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 652, 'parent_id' => 421, 'lev1' => 4, 'lev2' => 2, 'lev3' => 1, 'lev4' => 5, 'kode_akun' => '4.2.01.05', 'nama_akun' => 'Pendapatan Non Usaha Lainnya', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 653, 'parent_id' => 431, 'lev1' => 4, 'lev2' => 3, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '4.3.01.01', 'nama_akun' => 'Pendapatan revaluasi Aset', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 654, 'parent_id' => 431, 'lev1' => 4, 'lev2' => 3, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '4.3.01.02', 'nama_akun' => 'Pendapatan revaluasi Saham', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 655, 'parent_id' => 431, 'lev1' => 4, 'lev2' => 3, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '4.3.01.03', 'nama_akun' => 'Pendapatan Non Usaha Lainnya', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 656, 'parent_id' => 511, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '5.1.01.01', 'nama_akun' => 'Gaji Pegawai Tetap', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 657, 'parent_id' => 511, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '5.1.01.02', 'nama_akun' => 'Gaji pegawai teknisi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 658, 'parent_id' => 511, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '5.1.01.03', 'nama_akun' => 'Gaji Cater', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 659, 'parent_id' => 511, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 5, 'kode_akun' => '5.1.01.04', 'nama_akun' => 'Honor Pembina', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 660, 'parent_id' => 511, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 5, 'kode_akun' => '5.1.01.05', 'nama_akun' => 'Honor Pengawas', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 661, 'parent_id' => 512, 'lev1' => 5, 'lev2' => 1, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '5.1.02.01', 'nama_akun' => 'Beban Tunjangan Pegawai', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 662, 'parent_id' => 512, 'lev1' => 5, 'lev2' => 1, 'lev3' => 2, 'lev4' => 2, 'kode_akun' => '5.1.02.02', 'nama_akun' => 'Beban Lembur Pegawai', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 663, 'parent_id' => 513, 'lev1' => 5, 'lev2' => 1, 'lev3' => 3, 'lev4' => 1, 'kode_akun' => '5.1.03.01', 'nama_akun' => 'Beban Administrasi dan Umum', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 664, 'parent_id' => 513, 'lev1' => 5, 'lev2' => 1, 'lev3' => 3, 'lev4' => 2, 'kode_akun' => '5.1.03.02', 'nama_akun' => 'Beban Sewa Kantor', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 665, 'parent_id' => 513, 'lev1' => 5, 'lev2' => 1, 'lev3' => 3, 'lev4' => 3, 'kode_akun' => '5.1.03.03', 'nama_akun' => 'Beban Pemeliharaan & Perbaikan Aset', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 666, 'parent_id' => 514, 'lev1' => 5, 'lev2' => 1, 'lev3' => 4, 'lev4' => 1, 'kode_akun' => '5.1.04.01', 'nama_akun' => 'Beban Rapat', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 667, 'parent_id' => 514, 'lev1' => 5, 'lev2' => 1, 'lev3' => 4, 'lev4' => 2, 'kode_akun' => '5.1.04.02', 'nama_akun' => 'Beban Peningkatan Kapasitas', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 668, 'parent_id' => 515, 'lev1' => 5, 'lev2' => 1, 'lev3' => 5, 'lev4' => 1, 'kode_akun' => '5.1.05.01', 'nama_akun' => 'Beban Transportasi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 669, 'parent_id' => 515, 'lev1' => 5, 'lev2' => 1, 'lev3' => 5, 'lev4' => 2, 'kode_akun' => '5.1.05.02', 'nama_akun' => 'Beban SPPD', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 670, 'parent_id' => 516, 'lev1' => 5, 'lev2' => 1, 'lev3' => 6, 'lev4' => 1, 'kode_akun' => '5.1.06.01', 'nama_akun' => 'Beban Penyisihan Kerugian Piutang', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 671, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 1, 'kode_akun' => '5.1.07.01', 'nama_akun' => 'Beban Penyusutan Gedung dan Bangunan', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 672, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 2, 'kode_akun' => '5.1.07.02', 'nama_akun' => 'Beban Penyusutan Kendaraan & Mesin', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 673, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 3, 'kode_akun' => '5.1.07.03', 'nama_akun' => 'Beban Penyusutan Inventaris', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 674, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 4, 'kode_akun' => '5.1.07.04', 'nama_akun' => 'Beban Amortisasi Biaya Pendirian Organisasi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 675, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 5, 'kode_akun' => '5.1.07.05', 'nama_akun' => 'Beban Amortisasi Lisensi', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 676, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 6, 'kode_akun' => '5.1.07.06', 'nama_akun' => 'Beban Amortisasi Sewa dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 677, 'parent_id' => 517, 'lev1' => 5, 'lev2' => 1, 'lev3' => 7, 'lev4' => 7, 'kode_akun' => '5.1.07.07', 'nama_akun' => 'Beban Amortisasi Asuransi dibayar dimuka', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 678, 'parent_id' => 519, 'lev1' => 5, 'lev2' => 1, 'lev3' => 9, 'lev4' => 1, 'kode_akun' => '5.1.09.01', 'nama_akun' => 'Beban Operasional Lain-lain', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 679, 'parent_id' => 521, 'lev1' => 5, 'lev2' => 2, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '5.2.01.01', 'nama_akun' => 'Beban Belanja Barang Dagang', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 680, 'parent_id' => 531, 'lev1' => 5, 'lev2' => 3, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '5.3.01.01', 'nama_akun' => 'Beban Pajak Bank', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 681, 'parent_id' => 531, 'lev1' => 5, 'lev2' => 3, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '5.3.01.02', 'nama_akun' => 'Beban Administrasi Bank', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 682, 'parent_id' => 532, 'lev1' => 5, 'lev2' => 3, 'lev3' => 2, 'lev4' => 1, 'kode_akun' => '5.3.02.01', 'nama_akun' => 'Beban Penghapusan Aset Tetap dan Inventaris', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 683, 'parent_id' => 533, 'lev1' => 5, 'lev2' => 3, 'lev3' => 3, 'lev4' => 1, 'kode_akun' => '5.3.03.01', 'nama_akun' => 'Beban Non Usaha Lainnya', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 684, 'parent_id' => 541, 'lev1' => 5, 'lev2' => 4, 'lev3' => 1, 'lev4' => 1, 'kode_akun' => '5.4.01.01', 'nama_akun' => 'Taksiran PPh', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 685, 'parent_id' => 212, 'lev1' => 5, 'lev2' => 2, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '2.1.02.02', 'nama_akun' => 'Utang FEE Kolektor', 'jenis_mutasi' => 'Kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 686, 'parent_id' => 113, 'lev1' => 5, 'lev2' => 1, 'lev3' => 1, 'lev4' => 3, 'kode_akun' => '1.1.03.01', 'nama_akun' => 'Piutang Usaha', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 687, 'parent_id' => 211, 'lev1' => 5, 'lev2' => 2, 'lev3' => 1, 'lev4' => 4, 'kode_akun' => '2.1.01.04', 'nama_akun' => 'Utang Bonus', 'jenis_mutasi' => 'kredit', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 688, 'parent_id' => 512, 'lev1' => 5, 'lev2' => 5, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '5.1.02.03', 'nama_akun' => 'Beban Bonus Prestasi Kerja', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
            ['id' => 689, 'parent_id' => 512, 'lev1' => 5, 'lev2' => 5, 'lev3' => 1, 'lev4' => 2, 'kode_akun' => '5.1.02.04', 'nama_akun' => 'Beban FEE Kolektor', 'jenis_mutasi' => 'debet', 'tgl_nonaktif' => null, 'created_at' => null, 'updated_at' => null],
        ];

        DB::table('accounts')->insert($data);
    }
}
