<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InventorySampleSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $data = [
            // Tanah (kategori 1)
            [
                'nama_barang' => 'Tanah Kantor Pusat',
                'tgl_beli' => '2020-01-15',
                'unit' => '1',
                'harset' => 500000000,
                'harsat' => 500000000,
                'umur_ekonomis' => 0,
                'jenis' => '1',
                'kategori' => '1',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Gedung & Bangunan (kategori 2)
            [
                'nama_barang' => 'Gedung Kantor PDAM',
                'tgl_beli' => '2021-06-10',
                'unit' => '1',
                'harset' => 1200000000,
                'harsat' => 1200000000,
                'umur_ekonomis' => 240,
                'jenis' => '1',
                'kategori' => '2',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Gudang Material Utara',
                'tgl_beli' => '2022-03-20',
                'unit' => '1',
                'harset' => 350000000,
                'harsat' => 350000000,
                'umur_ekonomis' => 240,
                'jenis' => '1',
                'kategori' => '2',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Kendaraan & Mesin (kategori 3)
            [
                'nama_barang' => 'Pickup Suzuki Carry',
                'tgl_beli' => '2023-02-05',
                'unit' => '2',
                'harset' => 180000000,
                'harsat' => 180000000,
                'umur_ekonomis' => 96,
                'jenis' => '1',
                'kategori' => '3',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Pompa Air Grundfos 7.5kW',
                'tgl_beli' => '2022-08-12',
                'unit' => '3',
                'harset' => 25000000,
                'harsat' => 25000000,
                'umur_ekonomis' => 96,
                'jenis' => '1',
                'kategori' => '3',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Generator Set 50kVA',
                'tgl_beli' => '2021-11-25',
                'unit' => '1',
                'harset' => 95000000,
                'harsat' => 95000000,
                'umur_ekonomis' => 120,
                'jenis' => '1',
                'kategori' => '3',
                'status' => 'Rusak',
                'tgl_validasi' => '2025-04-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // Inventaris / Peralatan (kategori 4)
            [
                'nama_barang' => 'Komputer PC Admin',
                'tgl_beli' => '2024-01-15',
                'unit' => '10',
                'harset' => 8500000,
                'harsat' => 8500000,
                'umur_ekonomis' => 48,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Laptop Dell Latitude',
                'tgl_beli' => '2024-05-20',
                'unit' => '5',
                'harset' => 12500000,
                'harsat' => 12500000,
                'umur_ekonomis' => 48,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Printer Epson L3210',
                'tgl_beli' => '2023-07-08',
                'unit' => '4',
                'harset' => 2800000,
                'harsat' => 2800000,
                'umur_ekonomis' => 48,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Meja Kerja Staff',
                'tgl_beli' => '2022-12-01',
                'unit' => '15',
                'harset' => 1500000,
                'harsat' => 1500000,
                'umur_ekonomis' => 60,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Kursi Putar Staff',
                'tgl_beli' => '2022-12-01',
                'unit' => '15',
                'harset' => 750000,
                'harsat' => 750000,
                'umur_ekonomis' => 60,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Lemari Arsip Besi',
                'tgl_beli' => '2020-09-15',
                'unit' => '8',
                'harset' => 2200000,
                'harsat' => 2200000,
                'umur_ekonomis' => 60,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Dijual',
                'tgl_validasi' => '2025-02-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'AC Split Daikin 1PK',
                'tgl_beli' => '2023-04-12',
                'unit' => '6',
                'harset' => 4500000,
                'harsat' => 4500000,
                'umur_ekonomis' => 60,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Baik',
                'tgl_validasi' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nama_barang' => 'Proyektor Epson EB-X51',
                'tgl_beli' => '2023-08-22',
                'unit' => '2',
                'harset' => 6800000,
                'harsat' => 6800000,
                'umur_ekonomis' => 48,
                'jenis' => '1',
                'kategori' => '4',
                'status' => 'Hilang',
                'tgl_validasi' => '2025-09-01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('inventories')->truncate();
        DB::table('inventories')->insert($data);

        $this->command->info('✓ Inventories seeded: ' . count($data) . ' rows');
    }
}